name: Maven release to OSSRH

on:
    workflow_dispatch:
        inputs:
            releaseVersion:
                description: 'Release version'
                required: true
                default: x.y.z
            newSnapshotVersion:
                description: 'New snapshot version'
                required: true
                default: x.y.z-SNAPSHOT

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Java
                uses: actions/setup-java@v2
                with:
                    java-version: '8'
                    distribution: 'zulu'
                    cache: maven
                    server-id: ossrh
                    server-username: OSSRH_USERNAME
                    server-password: OSSRH_PASSWORD
                    gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
                    gpg-passphrase: MAVEN_GPG_PASSPHRASE

            -   name: Configure Git User
                run: |
                    git config user.email "actions@github.com"
                    git config user.name "GitHub Actions"

            -   name: Publish package to local GH repository
                run: mvn release:prepare release:perform -Prelease -B -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.newSnapshotVersion }}
                env:
                    MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
                    OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                    OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

            -   name: Push tag
                run: git push ; git push --tags
